name: Deploy on changes

on:
  push:
    branches:
      - main

jobs:
  ## ###############
  ## Deploy frontend changes
  ## ###############
  deploy-frontend:
    name: Deploy frontend changes
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Clones repo to the commit that triggered the event
      - name: Cloning repository
        uses: actions/checkout@v3

      # Set up node and install frontend dependencies
      - name: Set up Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      # Install dependencies with failover
      - name: Install dependencies with cache
        id: depinstall
        run: npm ci --loglevel verbose
        continue-on-error: true
      - name: Install dependencies without cache
        run: npm install

      # Build frontend files
      - name: Build website files
        env:
          NODE_ENV: production
          CI: false
        run: npm run build

      # Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
